[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "asana"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Project Management", "Cost/Freemium", "Task Management", "Vendor/Asana", "Area/Project Management", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-asana"

[build-options]
observabilityIncluded = true
